### ISSUE TITLE
RWA Export Result

### ISSUE THREAD

**Issue by benediktwetzel** [martinctc/rwa#14]
Thanks for your great work!

I m using this [website](https://rwa-web.shinyapps.io/multipleregression/) and have an issue exporting my results. An export option is not displayed. Where you part of the development of this website? and could help me?

**Comment by martinctc** [comment]
Hi @benediktwetzel, the outputs can be accessed as data frames in R, which you can export in csv or Excel or in any other way you want. 

An example could be: 
```R
library(rwa)
library(tidyverse)

rwa_output <-
  mtcars %>%
  rwa(outcome = "mpg",
      predictors = c("cyl", "disp", "hp", "gear"),
      applysigns = TRUE)

rwa_results <- rwa_output$result
```
`rwa_results` is the main data frame that you're most likely wanting to export. 

You can then use:
- `write.csv()`: base function for writing the data frame to csv
- `writexl::write_xlsx()`: write the data frame to an xlsx file
- `vivainsights::export()`: copy the data frame to clipboard

Note that for the above, you will have to install the packages `writexl` or `vivainsights` to use those specific functions.
