### ISSUE TITLE
Data file problem

### ISSUE THREAD

**Issue by maipham123** [martinctc/rwa#3]
Hi, 

May I ask: In the data file, did you put the correlation matrix in? Or did you put the mean-centered of each variable? 
I did not find any specification about the data file and would really appreciate your help. Thank you. 

Mai

**Comment by martinctc** [comment]
Hi Mai, the data file to pass in would not require any processing before running `rwa()`. A correlation matrix is calculated within the function itself. There is an example in the documentation where you could run this with **diamonds** dataset from **ggplot2**, so you can see what the data could look like:

```
rwa(diamonds,"price",c("depth","carat"))
```

Does this help? Please let me know so I can try to improve the documentation to make this clearer.

**Comment by maipham123** [comment]
Hi,

Thank you so much for the fast reply! I think it's a bit confusing whether
the data file is a raw data or not (from your reference and the JavaScript
link you provide at the end of the introduction page). Otherwise, I now
understand that the dataset is a raw data file and the function will
calculate the correlation matrix for me. Thank you so much for your
fantastic work!

Mai
